### ISSUE TITLE
Double Mention Button on Vocal Channels

### ISSUE THREAD

**Issue by Airwayx** [Echological/MentionChannels#9]
Hello,
When you right click on Vocal Channels to mention it two "Mention" buttons appear instead of just one as on the text channels.
You can still mention the vocal channel but yeah it's a display bug.
See screenshot:
![image](https://user-images.githubusercontent.com/70035113/156901943-7132e311-2782-4904-a80d-89d807f85374.png)

**Comment by Echological** [comment]
Will check it out

**Comment by Echological** [comment]
Seems for some reason discord added a "Mark As Read" button to voice channels, which is weird because voice channels cannot be read. The plugin added a Mention button above the "Mark As Read" to handle text channels, and the "Show Names" button to handle voice channels. I will remove the "Show Names" one so it only applies once.
